import { Activity, AlertTriangle, Box, Clock3, Gauge, Search, ThumbsUp } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../../lib/api'

function Stat({icon:Icon,label,value,sub}:{icon:any;label:string;value:any;sub?:string}){return <div className="stat-card"><div className="stat-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{value ?? '—'}</strong>{sub&&<small>{sub}</small>}</div></div>}

export default function Dashboard(){const q=useQuery({queryKey:['admin-dashboard'],queryFn:api.adminDashboard,refetchInterval:30000});const d=q.data;if(q.isLoading)return <AdminLoading/>;return <div><AdminTitle title="Overview" subtitle="Recommendation health, usage and latest system activity."/><div className="stats-grid"><Stat icon={Box} label="Products" value={Number(d?.stats?.products||0).toLocaleString()}/><Stat icon={Search} label="Searches today" value={d?.stats?.searches_today}/><Stat icon={Clock3} label="Avg latency" value={`${d?.stats?.avg_latency_ms||0} ms`} sub={`P95 ${d?.stats?.p95_latency_ms||0} ms`}/><Stat icon={Gauge} label="Zero result rate" value={`${d?.stats?.zero_result_rate||0}%`}/><Stat icon={ThumbsUp} label="Feedback positive" value={d?.stats?.feedback_positive_rate==null?'—':`${d.stats.feedback_positive_rate}%`}/><Stat icon={AlertTriangle} label="Errors today" value={d?.stats?.errors_today}/></div><div className="admin-grid-two"><section className="admin-panel"><div className="panel-head"><div><h2>Search activity</h2><p>Last seven days</p></div><Activity size={18}/></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><AreaChart data={d?.searches_by_day||[]}><defs><linearGradient id="searchFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="currentColor" stopOpacity={0.28}/><stop offset="95%" stopColor="currentColor" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickLine={false}/><YAxis allowDecimals={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="count" stroke="currentColor" fill="url(#searchFill)"/></AreaChart></ResponsiveContainer></div></section><section className="admin-panel"><div className="panel-head"><div><h2>Top queries</h2><p>Most repeated user intent</p></div></div><div className="rank-list">{(d?.top_queries||[]).map((x:any,i:number)=><div key={x.query}><span>{String(i+1).padStart(2,'0')}</span><strong>{x.query}</strong><em>{x.count}</em></div>)}{!(d?.top_queries||[]).length&&<div className="muted">No searches recorded yet.</div>}</div></section></div>{d?.latest_ingestion&&<section className="admin-panel ingestion-summary"><div><span className="status-dot"/><div><h2>Latest ingestion</h2><p>{d.latest_ingestion.filename}</p></div></div><div className="ingestion-progress"><div><span>{d.latest_ingestion.status}</span><strong>{Number(d.latest_ingestion.processed).toLocaleString()} records</strong></div><div className="progress-track"><i style={{width:`${d.latest_ingestion.progress_percent}%`}}/></div></div></section>}</div>}

export function AdminTitle({title,subtitle}:{title:string;subtitle:string}){return <div className="admin-title"><div><span className="section-kicker">SemanticFit admin</span><h1>{title}</h1><p>{subtitle}</p></div></div>}
export function AdminLoading(){return <div><AdminTitle title="Loading" subtitle="Fetching system data..."/><div className="admin-panel skeleton" style={{height:220}}/></div>}
